          name: Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repo checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # Node setup
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Build web app
      - name: Build project
        run: npm run build

      # Install Capacitor
      - name: Install Capacitor
        run: npm install @capacitor/core @capacitor/cli

      # Init Capacitor
      - name: Init Capacitor
        run: npx cap init pos.app com.pos.app --web-dir=dist

      # Add Android platform
      - name: Add Android
        run: npx cap add android

      # Copy build files
      - name: Copy files
        run: npx cap copy

      # Build APK
      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      # Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
